services:
  db:
    image: postgres:16
    container_name: auth_db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: auth_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://db:5432/app
      DB_USER: app
      DB_PASS: app
      JWT_SECRET: your-very-long-secret-key-that-is-at-least-32-characters-long
      ACCESS_TOKEN_MINUTES: "15"
      REFRESH_TOKEN_DAYS: "7"
      COOKIE_SECURE: "false"
      COOKIE_SAMESITE: Lax
      CORS_ALLOWED_ORIGINS: http://localhost:3000,http://127.0.0.1:3000
    ports:
      - "8080:8080"

  adminer:
    image: adminer
    container_name: auth_adminer
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
